### ISSUE TITLE
Can't switch because kernel is not pushed

### ISSUE THREAD

**Issue by jbarthelmes** [DBCDK/morph#109]
When trying to `morph deploy deployment.nix switch` I get the following error:

```
Traceback (most recent call last):
  File "/nix/store/x3j6bjjprvn120pgfi97c7m32n7wiyjj-systemd-boot-builder.py", line 240, in <module>
    main()
  File "/nix/store/x3j6bjjprvn120pgfi97c7m32n7wiyjj-systemd-boot-builder.py", line 209, in main
    write_entry(*gen, machine_id)
  File "/nix/store/x3j6bjjprvn120pgfi97c7m32n7wiyjj-systemd-boot-builder.py", line 91, in write_entry
    kernel = copy_from_profile(profile, generation, "kernel")
  File "/nix/store/x3j6bjjprvn120pgfi97c7m32n7wiyjj-systemd-boot-builder.py", line 67, in copy_from_profile
    copy_if_not_exists(store_file_path, "/boot/efi%s" % (efi_file_path))
  File "/nix/store/x3j6bjjprvn120pgfi97c7m32n7wiyjj-systemd-boot-builder.py", line 21, in copy_if_not_exists
    shutil.copyfile(source, dest)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/454ar0mw1pjylarz448siildaxib5ml9-linux-4.19.106/bzImage'
```

In `kernel = copy_from_profile(profile, generation, "kernel")` the python script tries to access `/nix/store/fvwl1bib1msl81c8x7khl3s07bdv4s1b-nixos-system-tiamat-19.09pre-git/kernel`, which is a symlink to `/nix/store/454ar0mw1pjylarz448siildaxib5ml9-linux-4.19.106/bzImage`.

That path is built on my machine but not copied to the target. The symlink seems to be copied but without recurring on its destination. Could this be a bug in `nix copy` or whatever it's called?

**Comment by jbarthelmes** [comment]
Steps to reproduce:
1. Create `deployment.nix` as
```nix
let
  pkgs = import (builtins.fetchTarball {
    # 19.09
    url = https://github.com/NixOS/nixpkgs-channels/archive/ce9f1aaa39ee2a5b76a9c9580c859a74de65ead5.tar.gz;
    sha256 = "1s2b9rvpyamiagvpl5cggdb2nmx4f7lpylipd397wz8f0wngygpi";
  }) {};
in
{
  network = {
      description = "Issue109";
      inherit pkgs;
  };

  "<hostname>" = { config, pkgs, ... }: {
    fileSystems = {
      "/" = {
        device = "/dev/sda1";
        fsType = "ext2";
      };
      "/boot" = {
        device = "/dev/sda2";
        fsType = "fat";
      };
    };

    boot.loader.systemd-boot.enable = true;
  };
}
```
2. Set `<hostname>`. File system and partitions need not match the configuration. Only `/boot` needs to be a directory.
3. Run `morph deploy deployment.nix boot` or `switch`. You should get the mentioned error.

The `/nix/store/*-nixos-system-<hostname>*/kernel` should point to some `/nix/store/*-linux-4.19.06/bzImage`, which is present on the building machine, but not on <hostname>.

**Comment by srhb** [comment]
I cannot reproduce this using morph f73a04566a9aae3b91db007587c216b03ed1a335 and nix 2.3.3. The fact that the symlink is there and somehow the target isn't sounds like either a bug in nix (which I haven't seen) or store/db corruption on the target side. I would suggest that you try to verify that your store is healthy before continuing, and then I'll be happy to try to reproduce again with your version of Nix/morph if you provide those. :)

See the nix-store manual for verification, something like `nix-store --verify --check-contents` will probably be what you want here.

**Comment by srhb** [comment]
Actually, throw that in on the source side as well for good measure. I think verification does happen on the target, but I'm not absolutely sure, so it's probably unnecessary -- but might as well.

**Comment by jbarthelmes** [comment]
`nix-store --verify` revealed that the mentioned kernel store path was modified. This issue is solved. However, I think `nix copy` should print a warning in this case?

**Comment by srhb** [comment]
I'm pretty sure it would be prohibitively expensive for Nix to verify every path that is _already present_ whenever another path refers to it, which is essentially what it would take to catch it in this case. I'm sure upstream will be very unlikely to make that trade. The problem is that you're either experiencing filesystem corruption, or some of the Nix write barriers were broken somehow. I'm sorry I probably can't get you any better story here.

**Comment by jbarthelmes** [comment]
The issue is that the receiver seems to have detected the wrong hash, but the sender didn't and also wasn't informed.

**Comment by jbarthelmes** [comment]
>every path that is already present
Sorry, but I left out that that path was corrupted on the sender.

So `nix copy` on the receiver notices that it was sent corrupted files, but fails silently by just not writing them and continuing with other store paths.

**Comment by srhb** [comment]
Thanks for the clarification. If `nix copy` knows that the receiver barfed while trying to register the path due to a hash mismatch, that could indeed be checked inexpensively. Might be worth filing an issue upstream. I'll probably experiment a bit later.
