### ISSUE TITLE
Morph doesn't support ssh on different ports

### ISSUE THREAD

**Issue by lovesegfault** [DBCDK/morph#110]
I have a number of machines at home all of which have sshd running on port 22, but to the outside world different ports are open and they get routed accordingly. 

I think morph should have a per-machine setting for which ssh port to use, but I would settle for the simpler solution of an `SSH_PORT` envvar as well.

**Comment by sorki** [comment]
Why not use standard `.ssh/config` ? You can even use `home-manager` to generate entries.

**Comment by zimbatm** [comment]
It's better if all the configuration is located in the same place. Things like port numbers are not user-specific unlike the ssh key and ssh user.

**Comment by sorki** [comment]
Well with Nix nothing prevents you to structure configuration to be in one place. IMHO it's better to rely on standard stuff than add features - they require code, maintenance, testing and documentation. Next time someone will ask for `ProxyCommand` or `ControlMaster`. :)

**Comment by Shados** [comment]
@zimbatm I too got annoyed at this, and [hacked around it](https://github.com/Shados/shim-getpw#self-contained-ssh-client-configuration). As mentioned there, you could use nss_wrapper to achieve the same if you'd prefer a hack with more than one user :P.

**Comment by zimbatm** [comment]
Nice hack :) It would be nice if OpenSSH allowed specifying the path to the `.ssh/config` file. My guess is that they didn't add that option for "security" reasons.

**Comment by johanot** [comment]
#112 is merged now. If we get #105 in as well, this issue should be closable? Or what do you think? :)

**Comment by lovesegfault** [comment]
#112 is sufficient for me, feel free to close AFAIC :)

**Comment by sorki** [comment]
For the reference I'm linking the home-manager module https://github.com/otevrenamesta/otevrenamesta-cz-configuration/blob/master/modules/deploy.nix
