### ISSUE TITLE
Jump servers for ssh

### ISSUE THREAD

**Issue by shmish111** [DBCDK/morph#145]
Currently I use ssh config to ensure that morph uses my jump/bastion servers that are required to ssh to the machines I want to deploy to. It would be much better if I could declare these jump servers in my morph config rather than relying on a user global file.

**Comment by wmertens** [comment]
You can pass a config file apparently, see #112

**Comment by srhb** [comment]
Closing this, if you think we should expand the ssh config options better, we can try to document a specific example :)
