### ISSUE TITLE
morph can't build a configuration using <nixpkgs/nixos/modules/virtualisation/amazon-image.nix>

### ISSUE THREAD

**Issue by exarkun** [DBCDK/morph#146]
Both morph and amazon-image.nix want to set `networking.hostName` to something.  Building this config fails.

This worked prior to https://github.com/DBCDK/morph/commit/e88558c277f0abc26eac9db7190110d7c9beca1c

The minimal config to reproduce this is nearly trivial:

```
{
  imports = [ <nixpkgs/nixos/modules/virtualisation/amazon-image.nix> ];                                                                         
  ec2.hvm = true;                                                                                                                                
}
```

**Comment by cstrahan** [comment]
Both morph and `amazon-image.nix` try to set a default value, and so the module system complains because it doesn't know how to break the tie.

This works:

```
  # morph plumbs the deployment target name (i.e. "example.com") through as the `name` argument,
  # so we can do this:
  "example.com" = { name, config, pkgs, modulesPath, ... }: {
    # set the name exmplicitly
    networking.hostName = name; # <--- note the lack of mkDefault

    imports = [ "${modulesPath}/virtualisation/amazon-image.nix" ];
    ec2.hvm = true;
  };
```

If you'd rather have the system use the hostname as configured during instance creation, use:

```
    networking.hostName = "";
```

**Comment by exarkun** [comment]
Okay.  That all seems true to me.  Did you mean to close the issue, too?  I'm not clear on whether you think this is acceptable behavior for morph and it will remain as-is or if you think it would be reasonable to make it work again (eg by having morph provide its value with a slightly higher or lower priority than the one used by mkDefault so that there is no unbreakable tie - while still allowing someone to explicitly set a hostname as demonstrated in the above comment).

Thanks.

**Comment by srhb** [comment]
I think it's better that the user make a decision explicitly in case of differing values here, though I'm not specifically familiar with the amazon module. If this isn't sensible (ie. it's always correct for one or the other to win priority-wise), please feel free to reopen and argue for that :)
