### ISSUE TITLE
Morph uses `nix copy` which doesn't use cache?

### ISSUE THREAD

**Issue by wmertens** [DBCDK/morph#150]
Not sure if this is a Nix or morph or configuration problem - I'm using morph v1.5.0 and to deploy, it calls `nix copy`.

It uploads the entire system from my deploy host, which is slow.

Is there a way to have it prefer binary caches?

**Comment by johanot** [comment]
@wmertens Perhaps `deployment.substituteOnDestination` is useable for you? https://github.com/DBCDK/morph/blob/master/README.md#advanced-configuration
