### ISSUE TITLE
SSH_CONFIG_FILE isn't used by `nix copy`

### ISSUE THREAD

**Issue by wmertens** [DBCDK/morph#152]
Looks like #112 doesn't help with deploying, because `nix copy` doesn't use `SSH_CONFIG_FILE` and therefore the store paths are not where they should be.

**Comment by srhb** [comment]
I thought this was fixed in #141

**Comment by srhb** [comment]
Yeah, we haven't cut a new release yet, but try master :)

**Comment by whentze** [comment]
Morph 1.6, which has that fix, is out and [available in NixOS 21.05](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/tools/package-management/morph/default.nix#L5).
