### ISSUE TITLE
error: syntax error, unexpected $undefined, expecting $end, at (string):1:52

### ISSUE THREAD

**Issue by spinus** [DBCDK/morph#154]
I have error message 
```
$ morph build ./sd.nix
error: syntax error, unexpected $undefined, expecting $end, at (string):1:52
Error while running `nix eval ..`: exit status 1
```
every time I'm executing any morph command for correct nix file (empty, {}, or just proper morph config).

I'm using nixpkgs unstable, morph version 1.5.0 and 1.4.0 (from nixpkgs-20.03) tried. `--show-trace` or `--dry-run` do not change anything.

Steps to reproduce:
```
nix-shell --pure -p morph nix
echo "{}" > ./file.nix
morph build ./file.nix
```

Any idea what is causing that issue?

**Comment by johanot** [comment]
What happens if you drop `--pure`, i.e. `nix-shell -p morph nix` ?

Alternatively, set either NIX_PATH=nixpkgs=<somepkgs> in your environment or `network.pkgs = import <somepkgs>;` in file.nix ?

**Comment by spinus** [comment]
Without `--pure` it's the same as without.
I tried setting NIX_PATH to a lot of different settings, channels, even old ones also unsetting it completely (that's why I ended up with `--pure`). Same effect.
Setting `network.pkgs` doesn't make sense here I think, it looks like the error is before the file is read, I can do `morph build ./Makefile` and effect is the same.

**Comment by spinus** [comment]
morph is probably using some internal "string" that contains some nix, or it autogenerates invalid one or importing from somewhere, is there any easy way I can turn debug mode and see what's going on or run morph with a debuger? (I don't have much go exp)

**Comment by spinus** [comment]
It looks like `--show-trace` is propagated to `cmd` but output is not properly redirected or read.

I added to nix/nix.go in line 201 (just before executing `cmd.Run()` and it gave me that:
```
fmt.Println(fmt.Sprintf("%+q", cmd));
fmt.Println(fmt.Sprintf("%+q", args));
```
```
/run/current-system/sw/bin/nix eval -f /tmp/morph-244830364/morph/eval-machines.nix info.deployment --arg networkExpr ./network.nix --json --show-trace
```
My next step is to get eval-machines file. Changing ./network.nix to any file that exist change nothing.

**Comment by spinus** [comment]
OK, finally I redirected stderr to stderr from `nix eval` and got this:
```
error: while evaluating 'flip' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/trivial.nix:138:16, called from /tmp/morph-100821863/morph/eval-machines.nix:80:7:
```
Looks like it morph has some specific dependency which is coming from NIX_PATH and it breaks with latest nixpkgs unstable.

Any suggestion what is best way to fix it? Do you guys want to support multiple nixpkgs versions or maybe handle it different way?

**Comment by srhb** [comment]
We think this looks much better with Nix 2.4, please reopen if you think that's not the case and we have work to do in morph itself.
