### ISSUE TITLE
`nix eval` steps don't respect `deployment.nixConfig`, breaking usage with `nixUnstable`

### ISSUE THREAD

**Issue by cole-h** [DBCDK/morph#156]
When using `nixUnstable`, you need to pass `--experimental-features nix-command` to use `nix eval` -- if you have this in your `deployment.nixConfig`, it works for everything except the `nix eval` steps.

I'm currently working around this by creating a nix config file for the project and setting `NIX_USER_CONF_FILES=$PWD/nix-conf`, where `nix-conf` only contains `experimental-features = nix-command`.

(I'd imagine this might be because `nix eval` is used to get the `nixConfig` in the first place...)

**Comment by srhb** [comment]
This should be fixed in #175 (pending release)

Let us know if it's not the case. :slightly_smiling_face:
