### ISSUE TITLE
question: deploy switch --rollback

### ISSUE THREAD

**Issue by jsoo1** [DBCDK/morph#164]
I'd love to be able to rollback a deployment. Can the --rollback flag be sent with deploy/switch?

**Comment by dminuoso** [comment]
Couldn't you just do
```
morph exec ./network.nix nixos-rebuild switch --rollback
```

**Comment by srhb** [comment]
I don't think we want to add a --rollback switch. If anything, maybe `morph rollback` is less overloaded. However, right now morph does very little profile manipulation, and I think that's a good thing. We could document the manual method of doing a rollback (ie. with `morph exec`) if needed. That would be welcome. :)
