### ISSUE TITLE
Pass build options to nix

### ISSUE THREAD

**Issue by piegamesde** [DBCDK/morph#165]
I frequently need to set some build options in order to orchestrate the machines on which I want to build my configuration. Apparently, morph has no possibility to pass down options to nix?

**Comment by srhb** [comment]
Does https://github.com/DBCDK/morph#advanced-configuration help?

**Comment by piegamesde** [comment]
It certainly does, but I think some CLI flags for ad-hoc situations would be good to have too.

**Comment by srhb** [comment]
We're sympathetic to this use-case, but the way morph does "multiple things" at a time (eg. eval + build in "deploy") it makes it a little unclear what the UX should be for "eval option" versus "build option" etc. If you can come up with some concrete examples, we'd love to think about it more.
