### ISSUE TITLE
Require Nix 2.4?

### ISSUE THREAD

**Issue by wmertens** [DBCDK/morph#179]
I saw that #175 had to revert some things to allow using Nix 2.3.

However, AFAIK 2.4 is backwards compatible with 2.3, and with Nix it's super easy to use 2.4 only for Morph.

How about requiring v2.4? Perhaps even using Nix to get it if it isn't in the path?

**Comment by aij** [comment]
I think that was actually to support Nix v2.4. The `nix` command was always experimental, with no claims to the stability of the interface. It was enabled by default in Nix v2.3, but is disabled in 2.4 unless explicitly enabled.

**Comment by wmertens** [comment]
Ah, so it doesn't matter if 2.4 is required by morph or not then, right? I'll close.
