### ISSUE TITLE
`bash: make-build: command not found`

### ISSUE THREAD

**Issue by nawordar** [DBCDK/morph#209]
I wanted to try out this tool for a more convenient way to push my NixOS configuration to a VM. I have almost no experience with Nix, so please be forgetful :smile:.

I cloned the repository and ran the `nix-shell --command make-build` command, exactly as shown in `README.md`. After downloading installing the packages I only got the message in the title. Am I doing something wrong?

**Comment by srhb** [comment]
Apologies, that instruction is definitely outdated. `nix-build` should suffice to build morph.

**Comment by nawordar** [comment]
Yes, `nix-build` works. Thank you
