### ISSUE TITLE
--upload-secrets does not honor SSH_USER, SSH_IDENTITY_FILE

### ISSUE THREAD

**Issue by sippeangelo** [DBCDK/morph#22]
The call to `scp` isn't passed the correct arguments to take `SSH_USER` and `SSH_IDENTITY_FILE` environment variables into account.

Since `scp` accepts the same arguments as `ssh`, the `initialSSHArgs` function should be able to be used just the same, with just a little reordering of the arguments.

**Comment by adamtulinius** [comment]
@johanot Please assign this to yourself if you start working on it. I'll probably fix it tomorrow if you haven't by then.
