### ISSUE TITLE
Cannot add path ... because it lacks a valid signature

### ISSUE THREAD

**Issue by PureW** [DBCDK/morph#56]
I'm trying to deploy to a Hetzner physical machine that was provisioned by nixops. I could build (`morph build deployment.nix`) and deploy secrets (`morph upload-secrets deployment.nix`) but the actual code deploy fails in this strange way. (At least it's strange to me, I'm fairly new to nix and morph/nixops).

```
xxx@nixos /h/e/e/morph> morph deploy deployment.nix test
Selected 1/1 hosts (name filter:-0, limits:-0):
          0: xxxx-amy (secrets: 1, health checks: 0)

/nix/store/gmv0xbbjk8liq3h29nwn2sqq7r0jxpgr-morph
nix result path:
/nix/store/gmv0xbbjk8liq3h29nwn2sqq7r0jxpgr-morph

Pushing paths to xxxx-amy:
        * /nix/store/zhsf6yycsyi9p809p9g1z7n31905mhwh-nixos-system-xxx-18.09pre-git
        * /nix/store/wvphz871j2sfz01k2pm1wxbp105kw55d-nixos-system-xxxx-18.09pre-git.drv
[2/0/686 copied (0.0/6.3 MiB)] copying path '/nix/store/0mhh8r6cv9hc3ml7fsclbcmz6riax225-healthcheck-commands.txt' to 'error: cannot add path '/nix/store/0mhh8r6cv9hc3ml7fsclbcmz6riax225-healthcheck-commands.txt' because it lacks a valid signature
error (ignored): unexpected end-of-file
error (ignored): writing to file: Broken pipe
error (ignored): writing to file: Broken pipe
[1 copied (1 failed) (0.0 MiB)]
error: unexpected end-of-file
xxx@nixos /h/e/e/morph>
```

**Comment by PureW** [comment]
Ahh I found `nix.requireSignedBinaryCaches = false;` which fixed this.

**Comment by johanot** [comment]
@PureW Won't recommend setting `nix.requireSignedBinaryCaches = false;` permanently. I only use it for exceptional cases like first-time provisioning. Consider instead `nix.trustedUsers = [ "@wheel" ];`, allowing members of group wheel only to push unsigned paths, or create a keypair and actually sign the paths you build. :-)

**Comment by PureW** [comment]
:+1: That sounds like good advice.
