### ISSUE TITLE
Missing documentation: build vs. push vs. deploy

### ISSUE THREAD

**Issue by joepie91** [DBCDK/morph#59]
It's not really clear from the README what the difference between these is.

My *guess* is that:

- `build` means evaluating the system configuration and building it into the local Nix store.
- `push` means uploading the Nix store items to the target system. Implicitly builds if needed.
- `deploy` means actually applying the system configuration that is made up of those uploaded store items, to the target system. Implicitly builds and pushes if needed.

... but I'm not sure that that guess is accurate.

**Comment by adamtulinius** [comment]
You're spot on, with the distinction that `deploy` has multiple sub-commands (`boot`, `switch`, ..), that works exactly like they do for e.g. `nixos-rebuild`.

Could you be persuaded to make a PR with your suggested changes? :-)

**Comment by johanot** [comment]
@joepie91 are you ok with #63 marking this as fixed? :-)

**Comment by joepie91** [comment]
Whoops, sorry for not responding again! I really should track my issues here more closely... but yeah, that change looks good, thanks @nhey :)

**Comment by johanot** [comment]
No hard feelings at all. I just assume silence means yes. :D Hope it's ok.
