### ISSUE TITLE
How to install this as a part of systemPackages?

### ISSUE THREAD

**Issue by joepie91** [DBCDK/morph#60]
The README states...

> Pre-built binaries are not provided, since we install morph through an overlay.

... but no instructions are provided on how to do this, and the `shell.nix` does not appear suitable for anything other than spawning an ad-hoc shell.

How does one make this part of their system configuration, such that `morph` is available as a system-wide binary?

**Comment by adamtulinius** [comment]
Hi there!

> How does one make this part of their system configuration, such that `morph` is available as a system-wide binary?

You have two options:

1) Morph is part of nixpkgs 19.03, so you can just install it as any normal package (https://nixos.org/nixos/packages.html#morph-1.2.0).

2) Since we rely on the latest and gratest version, we pin to a specific git revision like this in an overlay:

```
morph = with builtins; with super;
  let
      pin = fromJSON (readFile ../morph.json);
      checkout = fetchgit { inherit (pin) url rev sha256; };
  in
    callPackage "${checkout}/nix-packaging/default.nix" { version = pin.rev; }
```

with a `morph.json` like this:
```
{
  "url": "https://github.com/dbcdk/morph.git",
  "rev": "76fa9fc0f9b17c1be5c59c86b15145f7ff31788e",
  "date": "2019-05-08T14:05:11+02:00",
  "sha256": "01ah44naws6s0mq0x1kkxjhv2cpzlwd8wasb4kz1pylpmw7r3gjb",
  "fetchSubmodules": false
}
```

Hope that helps.

**Comment by joepie91** [comment]
Oops, apologies for not responding, I got a little occupied by other things. I've decided to take the overlay approach, minus the JSON file. For future reference by other people:

```nix
(self: super: {
	morph = let
		pin = {
			url = "https://github.com/dbcdk/morph.git";
			rev = "e08366d7ec139903c646c3114f4df4fd567f9947";
			sha256 = "19hz6y5za3i8w7m22wmpr37l4xiv9pjiyqm8frjznzx4k3jwjgvf";
		};

		checkout = super.fetchgit { inherit (pin) url rev sha256; };
	in
		super.callPackage "${checkout}/nix-packaging/default.nix" { version = pin.rev; };
})
```
