### ISSUE TITLE
Add option to archive /etc/nixos when using morph

### ISSUE THREAD

**Issue by mmahut** [DBCDK/morph#62]
I'm hiking about an option to archive/move ```/etc/nixos/configuration.nix``` when morph is touching the system, so whoever is connecting directly knows the ```/etc/nixos/configuration.nix``` is not used.

**Comment by johanot** [comment]
We've just added this to our config:
```
nix.nixPath =
  let
    rebuild-throw = pkgs.writeText "rebuild-throw.nix"
      ''throw "I'm sorry Dave, I'm afraid I can't do that... Please deploy this host with morph."'';
  in
    [ "nixos-config=${rebuild-throw}" ];
```
You could of course set `environment.etc."nixos/configuration.nix".source` as well. :)

Haven't really thought about building it into morph. If we do, I have a feeling it should be an opt-in thing.

**Comment by mmahut** [comment]
Thank you, that snipped is probably what we need :)
