### ISSUE TITLE
When `deployment.targetHost` is set it tries to build the wrong target

### ISSUE THREAD

**Issue by andir** [DBCDK/morph#77]
When specifying `deployment.targetHost` that is not equal to the attribute name of the server the build is empty.

example configuration:
```nix
{
  network.pkgs = import <nixpkgs> {};
  foo.deployment.targetHost = "1.1.1.1";
}
```

**Comment by fooker** [comment]
Looks like `targetHost` and the original name are mixed up a lot. `targetHost` is used all over the place where IMO the original name should be used.

It's not only that the build is empty: beside a lot of error messages and status outputs, the `--on='*'` filter works on the `targetHost`, not on the original name.
