### ISSUE TITLE
If --reboot is given --upload-secrets should be done after the reboot

### ISSUE THREAD

**Issue by mweinelt** [DBCDK/morph#99]
When deploying to a host and passing `--reboot` and `--upload-secrets` the secrets are deployed before rebooting, which doesn't make sense when deploying to volatile storage. Instead please upload the secrets after the reboot has finished.

Example log:
```
[hexa@gaia:~/git/hexa/nixos-servers]$ morph deploy config/default.nix boot --reboot --upload-secrets --on=helios.lossy.network
Selected 1/2 hosts (name filter:-1, limits:-0):
	  0: helios.lossy.network (secrets: 2, health checks: 0)

these derivations will be built:
  /nix/store/xb8lwh8pdxphc143x1b5xxpkjxhyd26r-morph.drv
building '/nix/store/xb8lwh8pdxphc143x1b5xxpkjxhyd26r-morph.drv'...
/nix/store/h7hyav57jw9p9m9kb5m89n2b5nxq8l6a-morph
nix result path: 
/nix/store/h7hyav57jw9p9m9kb5m89n2b5nxq8l6a-morph

Pushing paths to helios.lossy.network (@helios.lossy.network):
	* /nix/store/kz4k4yw6hnvwnrsin2wabm5d3wl50d4x-nixos-system-helios.lossy.network-19.09pre-git
copying path '/nix/store/lcsj6nwhf2pnw9j82f0r0spmick2ryp5-bind-9.14.9-man' from 'https://cache.nixos.org'...
copying path '/nix/store/50z37qm9ij90brs5fjvny3fskf0cczqz-bind-9.14.9-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/4ih5rin77afk09gf8n4crimxb0p4w12w-firmware' from 'https://cache.nixos.org'...
copying path '/nix/store/yh51mg28azshz680vrharja7w8iwjrc8-bind-9.14.9-host' from 'https://cache.nixos.org'...
copying path '/nix/store/1vm6cdpbp0wj187rzapsij7wzhd4c61r-jrpqx2yppvvr5hy6xsvzaqalrxf7dixm-source' from 'https://cache.nixos.org'...
copying path '/nix/store/3gw0vaq30spqg5ndicic6amhqmz57z6b-linux-4.19.95' from 'https://cache.nixos.org'...
copying path '/nix/store/jgh11psr8gvqdl3wnzccd2v266a0si1j-nixos-manpages' from 'https://cache.nixos.org'...
copying path '/nix/store/kdb5rmri32kcvc1cynsrpa2p8g7hf5h5-kernel-modules' from 'https://cache.nixos.org'...
copying path '/nix/store/0753ri56m1ksrcj0dggk53jsqh43q0c7-nixos-manual-html' from 'https://cache.nixos.org'...
copying path '/nix/store/iz0vgnyd23xy3px203hdjj4yzgd3k4am-nixos-help' from 'https://cache.nixos.org'...
[14 copied (17.9 MiB)]

Uploading secrets to helios.lossy.network (helios.lossy.network):
	* borgbackup-password (65 bytes).. OK
	* borgbackup-sshkey (399 bytes).. OK
Running healthchecks on helios.lossy.network (helios.lossy.network):
Health checks OK

Executing 'boot' on matched hosts:

** helios.lossy.network
updating GRUB 2 menu...

Asking host to reboot ... OK
Waiting for host to come online .ssh_exchange_identification: read: Connection reset by peer
...... OK
Running healthchecks on helios.lossy.network (helios.lossy.network):
Health checks OK
Done: helios.lossy.network
```

I'm using 0630d6bc83cd7bbad43628e2653ee65aeb357489

**Comment by adamtulinius** [comment]
Hi there,

Thanks for this suggestion. It's an interesting use case I don't think we've ever considered.

On the surface this seems to make a lot of sense -- can anybody think of any downsides to uploading secrets post reboot (when rebooting)?

(it should be done before running health checks, though).

**Comment by srhb** [comment]
This is already the behaviour NixOps has, so it sounds very sensible to me.

**Comment by johanot** [comment]
On the other hand, you might have units in the newly activated system that depend on the secrets being present. This is why morph currently upload secrets before anything else. But I agree with @adamtulinius in that, we probably never thought about the application of `--upload-secrets` and `--reboot` in conjunction. I guess it might be ok to have units failing on boot, as long as post-deploy actions and systemd restarts will make the system eventually consistent.

**Comment by johanot** [comment]
Related to my last comment:
You mention volatile storage. That sounds like a healthy mount is required before secret upload will succeed?

If done after reboot, should morph wait until systemd reports "no jobs pending" before trying to upload secrets? Currently, morph starts executing post-reboot actions as soon as the host is reachable via ssh. I see a potential deadlock, if secrets cannot be uploaded before the system is healthy, but the system might remain degraded until secrets are present.

**Comment by andir** [comment]
> Related to my last comment:
> You mention volatile storage. That sounds like a healthy mount is required before secret upload will succeed?
> 
> If done after reboot, should morph wait until systemd reports "no jobs pending" before trying to upload secrets? Currently, morph starts executing post-reboot actions as soon as the host is reachable via ssh. I see a potential deadlock, if secrets cannot be uploaded before the system is healthy, but the system might remain degraded until secrets are present.

You can probably just execute that with `systemd-run`:
```
systemd-run --wait --property=After=local-fs.target bash
```
(Note: I haven't tested that actual property name but it should be pretty close to what you want there)

The command will only finish once the `local-fs.target` has been reached and the command has been executed.

**Comment by grahamc** [comment]
If uploading before activating (before rebooting, when attached to a `boot` deploy) the secrets are uploaded and chown'd before the owning users exist, or worse: before temporary in-memory filesystems are loaded accidentally persisting secrets to disk.

**Comment by wmertens** [comment]
how about a systemd `secrets.target` that the system boots to first, which only completes when the secrets are uploaded? A

**Comment by grahamc** [comment]
We discussed this on Matrix and concluded with @Srhb that:

* the keys options will have an option per key:
   * uploadAt = 'post-activation' | 'pre-activation' (default);
* manually uploading secrets always uploads the secrets

**Comment by cole-h** [comment]
I've implemented the `uploadAt` option in https://github.com/DBCDK/morph/pull/158. Please take a look :)

**Comment by mweinelt** [comment]
Running the following before and for every secrets upload would probably do the trick:

```
systemd-run --wait --property=RequiresMountsFor=/run/keys/some/key.foo true
```

**Comment by mweinelt** [comment]
Implemented in https://github.com/DBCDK/morph/pull/161.
